apps/zone_meal_tracker_web/lib/zone_meal_tracker_web/router.ex
defmodule ZoneMealTrackerWeb.Router do
  use ZoneMealTrackerWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :authentication_required do
    plug ZoneMealTrackerWeb.Plugs.EnsureAuthenticated
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", ZoneMealTrackerWeb do
    pipe_through [:browser, :authentication_required]

    get "/", PageController, :index
  end

  scope "/", ZoneMealTrackerWeb do
    pipe_through :browser

    resources "/session", SessionController, only: [:new, :create, :delete], singleton: true
    resources "/users", UserController, only: [:new, :create]
  end

  if Mix.env() == :dev do
    forward "/sent_emails", Bamboo.SentEmailViewerPlug
  end

  # Other scopes may use custom stacks.
  # scope "/api", ZoneMealTrackerWeb do
  #   pipe_through :api
  # end
end

apps/zone_meal_tracker_web/lib/zone_meal_tracker_web/controllers/page_controller.ex
defmodule ZoneMealTrackerWeb.PageController do
  use ZoneMealTrackerWeb, :controller

  def index(conn, _params) do
    render(conn, "index.html")
  end
end

apps/zone_meal_tracker_web/lib/zone_meal_tracker_web/controllers/session_controller.ex
defmodule ZoneMealTrackerWeb.SessionController do
  use ZoneMealTrackerWeb, :controller

  alias ZoneMealTrackerWeb.Authentication
  alias ZoneMealTrackerWeb.SessionController.LoginForm

  def new(conn, _params) do
    changeset = LoginForm.changeset()
    render(conn, "new.html", changeset: changeset)
  end

  def create(conn, %{"login_form" => login_form_params}) do
    case LoginForm.run(login_form_params) do
      {:ok, user} ->
        conn
        |> Authentication.log_in(user)
        |> redirect(to: Routes.page_path(conn, :index))

      {:error, changeset} ->
        conn
        |> put_flash(:error, "Invalid email/password combination.")
        |> render("new.html", changeset: changeset)
    end
  end

  def delete(conn, _params) do
    conn
    |> Authentication.log_out()
    |> redirect(to: Routes.page_path(conn, :index))
  end
end

apps/zone_meal_tracker_web/lib/zone_meal_tracker_web/controllers/user_controller.ex
defmodule ZoneMealTrackerWeb.UserController do
  use ZoneMealTrackerWeb, :controller

  alias ZoneMealTrackerWeb.Authentication
  alias ZoneMealTrackerWeb.UserController.SignUpForm

  def new(conn, _params) do
    changeset = SignUpForm.changeset()
    render(conn, "new.html", changeset: changeset)
  end

  def create(conn, %{"sign_up_form" => sign_up_form_params}) do
    case SignUpForm.run(sign_up_form_params) do
      {:ok, user} ->
        conn
        |> Authentication.log_in(user)
        |> redirect(to: Routes.page_path(conn, :index))

      {:error, changeset} ->
        render(conn, "new.html", changeset: changeset)
    end
  end
end

apps/zone_meal_tracker_web/lib/zone_meal_tracker_web/views/error_view.ex
defmodule ZoneMealTrackerWeb.ErrorView do
  use ZoneMealTrackerWeb, :view

  # If you want to customize a particular status code
  # for a certain format, you may uncomment below.
  # def render("500.html", _assigns) do
  #   "Internal Server Error"
  # end

  # By default, Phoenix returns the status message from
  # the template name. For example, "404.html" becomes
  # "Not Found".
  def template_not_found(template, _assigns) do
    Phoenix.Controller.status_message_from_template(template)
  end
end

apps/zone_meal_tracker_web/lib/zone_meal_tracker_web/views/layout_view.ex
defmodule ZoneMealTrackerWeb.LayoutView do
  use ZoneMealTrackerWeb, :view

  alias ZoneMealTrackerWeb.Authentication

  def logged_in?(conn) do
    case Authentication.fetch_current_user(conn) do
      {:ok, _} -> true
      {:error, :unauthenticated} -> false
    end
  end
end

apps/zone_meal_tracker_web/lib/zone_meal_tracker_web/views/page_view.ex
defmodule ZoneMealTrackerWeb.PageView do
  use ZoneMealTrackerWeb, :view
end

apps/zone_meal_tracker_web/lib/zone_meal_tracker_web/views/session_view.ex
defmodule ZoneMealTrackerWeb.SessionView do
  use ZoneMealTrackerWeb, :view
end

apps/zone_meal_tracker_web/lib/zone_meal_tracker_web/views/user_view.ex
defmodule ZoneMealTrackerWeb.UserView do
  use ZoneMealTrackerWeb, :view
end

apps/zone_meal_tracker_web/lib/zone_meal_tracker_web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>ZoneMealTrackerWeb · Phoenix Framework</title>
    <link rel="stylesheet" href="<%= Routes.static_path(@conn, "/css/app.css") %>"/>
  </head>
  <body>
    <header>
      <section class="container">
        <nav role="navigation">
          <ul>
            <%= if logged_in?(@conn) do %>
              <li><%= link "Log out", to: Routes.session_path(@conn, :delete), method: :delete %></li>
            <% else %>
              <li><%= link "Sign up", to: Routes.user_path(@conn, :new) %></li>
              <li><%= link "Log in", to: Routes.session_path(@conn, :new) %></li>
            <% end %>
          </ul>
        </nav>
        <a href="http://phoenixframework.org/" class="phx-logo">
          <img src="<%= Routes.static_path(@conn, "/images/phoenix.png") %>" alt="Phoenix Framework Logo"/>
        </a>
      </section>
    </header>
    <main role="main" class="container">
      <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
      <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>
      <%= render @view_module, @view_template, assigns %>
    </main>
    <script type="text/javascript" src="<%= Routes.static_path(@conn, "/js/app.js") %>"></script>
  </body>
</html>

apps/zone_meal_tracker_web/lib/zone_meal_tracker_web/templates/page/index.html.eex
<section class="phx-hero">
  <h1><%= gettext "Welcome to %{name}!", name: "Phoenix" %></h1>
  <p>A productive web framework that<br/>does not compromise speed or maintainability.</p>
</section>

<section class="row">
  <article class="column">
    <h2>Resources</h2>
    <ul>
      <li>
        <a href="https://hexdocs.pm/phoenix/overview.html">Guides &amp; Docs</a>
      </li>
      <li>
        <a href="https://github.com/phoenixframework/phoenix">Source</a>
      </li>
      <li>
        <a href="https://github.com/phoenixframework/phoenix/blob/v1.4/CHANGELOG.md">v1.4 Changelog</a>
      </li>
    </ul>
  </article>
  <article class="column">
    <h2>Help</h2>
    <ul>
      <li>
        <a href="https://elixirforum.com/c/phoenix-forum">Forum</a>
      </li>
      <li>
        <a href="https://webchat.freenode.net/?channels=elixir-lang">#elixir-lang on Freenode IRC</a>
      </li>
      <li>
        <a href="https://twitter.com/elixirphoenix">Twitter @elixirphoenix</a>
      </li>
    </ul>
  </article>
</section>

apps/zone_meal_tracker_web/lib/zone_meal_tracker_web/templates/session/new.html.eex
<h1>Log in</h1>

<%= form_for @changeset, Routes.session_path(@conn, :create), fn f -> %>
    <%= if @changeset.action do %>
        <div class="alert alert-danger">
            <p>Oops, something went wrong! Please check the errors below.</p>
        </div>
    <% end %>

    <%= label f, :email %>
    <%= text_input f, :email %>
    <%= error_tag f, :email %>

    <%= label f, :password %>
    <%= password_input f, :password %>
    <%= error_tag f, :password %>

    <div>
        <%= submit "Log in" %>
    </div>
<% end %>

apps/zone_meal_tracker_web/lib/zone_meal_tracker_web/templates/user/form.html.eex
<%= form_for @changeset, @action, fn f -> %>
    <%= if @changeset.action do %>
        <div class="alert alert-danger">
            <p>Oops, something went wrong! Please check the errors below.</p>
        </div>
    <% end %>

    <%= label f, :email %>
    <%= text_input f, :email %>
    <%= error_tag f, :email %>

    <%= label f, :password %>
    <%= password_input f, :password %>
    <%= error_tag f, :password %>

    <div>
        <%= submit "Register" %>
    </div>
<% end %>

apps/zone_meal_tracker_web/lib/zone_meal_tracker_web/templates/user/new.html.eex
<h1>Sign Up</h1>

<%= render "form.html", Map.put(assigns, :action, Routes.user_path(@conn, :create)) %>